### ISSUE TITLE
Crash on paired device setting click

### ISSUE THREAD

**Issue by fcaronte** [choiman1559/NotiSender#14]
I have a question, is this app need Bluetooth connection phone to phone? Because I want to use old phone in the car for android auto connecting and I must force Bluetooth disabled using root to be able to keep main phone connected to car Bluetooth system, and I see today's that app crash when try to send a notification or o try to manage the second phone.

Edit: I try now on main phone with the other phone disconnected and crash too, so I think something is going wrong, i try to get a log near the fatal exception try to give a check of help or if need more log line.

![logcat_02-15-2024_19-47-25.txt](https://github.com/choiman1559/NotiSender/files/14301106/logcat_02-15-2024_19-47-25.txt)

**Comment by fcaronte** [comment]
I try to enable BT on other phone and crash persist so probably is not related to this

**Comment by choiman1559** [comment]
It seems that ProGuard was probably playing a prank during the release build. This issue does not occur in debug builds.

I think I've solved it in the commit below, but I'm not sure.
Could you please install the APK file in the attachment and see if the problem is resolved?

[app-release.zip](https://github.com/choiman1559/NotiSender/files/14306281/app-release.zip)
(After downloading the file, change the extension from ZIP -> APK and install.)

Related Commit: https://github.com/choiman1559/NotiSender/commit/86abec7d77dcbacc13f2ec0dc3ae6843aceea861

**Comment by fcaronte** [comment]
ok confirm seem fixed, thanks
