### ISSUE TITLE
[notifications were no more showing content]

### ISSUE THREAD

**Issue by eliascore** [choiman1559/NotiSender#19]
Hi there.. I found your app has been grow up into reliable app recently. remarkable and seamless, with less delay even though I used xiaomi device as second device and samsung as first device. I can receive notification with minimum delay on my first device. as my second device act as sender. but I found a slight change in notification details. I used to see the full content of notifications, for example WhatsApp notifications showing the detailed message content. but now, the WhatsApp notifications are only showing like this : Content ; 4 new messages. and if there are any new messages the notifications will be : Content ; 5 messages, and so on. instead of displaying the detail content of the messages it shows only numbers. Could you help me figure out what is wrong? It only happened if I use Xiaomi Redmi Note 9 as second device (sender) device. when I tried to change the second device using google pixel, the notification contents were showing correctly and in detailed form.

thanks for the attention and answer, I'd like to donate for this app since it grows better and better overtime. but still, this changing behaviour in notification details kinda makes me wonder

**Comment by choiman1559** [comment]
This is more likely due to Xiaomi MIUI's SystemUI implementation than a NotiSender issue.
Typically, some of these vendor custom OSs often modify Android to group multiple notifications from the same app into a single notification,
and since NotiSender receives notification information entirely through the system, it has no way of knowing if a single notification is being grouped, which seems to be the cause of this issue.

If this guess is true, there's nothing we can do about it (since it's Xiaomi's fault).
But please take a good look at your Xiaomi smartphone's notification-related system settings. There may be a setting related to this issue, such as "Notification Groups".
