### ISSUE TITLE
Login Alternate

### ISSUE THREAD

**Issue by tooliload** [choiman1559/NotiSender#4]
Is there a way to get a other Loginmethode? We dont have Google Login, because we dont have Google Services.

**Comment by choiman1559** [comment]
GMS is essential for FCM used for data exchange between devices in this app, so even if login bypass is possible, the app will not work without GMS.

See: https://stackoverflow.com/questions/37422538/does-firebase-cloud-messeging-requires-play-services

**Comment by SaifAqqad** [comment]
Since there's now the possibility of using backends other than fcm, is there any plans to support other login methods, or at least support signing in with google through the browser flow instead of the sdk?

this will remove the dependency on google play services, which will allow usage of the app on all android devices
