### ISSUE TITLE
Unable to pair new device

### ISSUE THREAD

**Issue by lucaslannes** [choiman1559/NotiSender#6]
Hello, thanks for the application!

I just installed the app on my device and my wife's device to share the notifications of the baby monitor (IPC360) but unfortunately I can't pair the devices.

I followed the steps to use the app and tried to pair the devices using the bluetooth but they don't appear on the available devices list.

What I need to do to pair the devices?

I'm also a developer so if you need some help to fix the issues I can help you.

**Comment by choiman1559** [comment]
Well, if you just want notification mirroring, you don't need to pair.  

Since pairing is a procedure for providing additional functions such as remote task execution, 
So, you do not need to set anything other than login, select mode, and toggling the main menu service for notification mirroring.

If you absolutely need pairing and pairing does not work, please contact again with a more detailed description of the problem.
