### ISSUE TITLE
How can I pair 2 devices without entering google account? or with different account? its very important for me. Thanks

### ISSUE THREAD

**Issue by Alex3040252** [choiman1559/NotiSender#8]
How can I pair 2 devices without entering google account? or with different account? its very important for me. Thanks

**Comment by choiman1559** [comment]
First at all, Pairing is a procedure for providing additional functions such as remote task execution, So, If you just want notification mirroring, you don't need to pair.

Second, because NotiSender uses your Google account information as an identifier between devices, the devices you want to communicate with must be logged into the same Google account. 

If you need to use it without logging in, try using RemoteSync (however, it does not provide notification synchronization function) : https://github.com/choiman1559/RemoteSync
