### ISSUE TITLE
[Bug] Remote player, Remote run

### ISSUE THREAD

**Issue by Iz-zzzzz** [choiman1559/NotiSender#9]
# App Setting
- Service & Account > Select service : "Now : hybrid"
- Send Options > Send Icon : Enable
- Send Options > Media control remote : Enable
- Send Options > Encrypt sending data : Enable

# Test devices
- Samsung Galaxy Note 10 lite (Android 13)
- Samsung Galaxy Tab S6 (Android 12)
- App Version : 1.19.6

# Bug
1. Remote media control always doesn't work
2. Player control at recipient device delays when changing music at sender device

https://github.com/choiman1559/NotiSender/assets/57972212/87db7688-226b-4e07-85ce-d10bb676091d

3. Remote run: when clicking at recipient device to launch remote run at sender device, It shows "Open with Playstore" options instead of run notification's task.

https://github.com/choiman1559/NotiSender/assets/57972212/8e01da63-4361-4f46-873c-96091c471e77

**Comment by choiman1559** [comment]
1. Remote media control == Player control. It looks like you are already using it.

2. Unlike other apps that use TCP/IP as a means of communication, NotiSender communicates using cloud push messaging so that you can use it anywhere on the planet as long as you have an internet connection. This guarantees high availability through NotiSender, but on the other hand, it has high ping and latency as a side effect during communication. According to our own research, communication takes ~50ms for one-way transmission and ~300ms for two-way reception/transmission. Considering this, the delay of media control seems unavoidable.

3. This problem occurs when the starting activity of the target app cannot be found. In other words, at least one activity using `android.intent.action.MAIN` must exist in the target app's Manifest, otherwise remote execution is not possible. This is usually the case for apps that are installed but do not show an icon in the launcher. (e.g. Google account settings)
